name: Continuous Integration

on: [push]

jobs:
  build:
    name: 'Build'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run build
  lint:
    name: 'Lint'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run lint
