name: Licensed

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v2
      - uses: jonabc/setup-licensed@v1
        with:
          version: 2.x
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: licensed status
